# -*- coding: utf-8 -*-
"""Python: AI Computer Vision With PyTorch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJPvPoONRpjj-7FTApD6zPmL0ox5d1-y
"""

# Import Dependencies

import torch
import torchvision

from torch import nn, optim
from torch.utils.data import DataLoader

from torchvision import datasets, transforms

transform = transforms.Compose([
    transforms.ToTensor()
])

train = datasets.MNIST(root = 'data' ,
                       train=True,
                       download=True,
                       transform=transform)
test = datasets.MNIST(root = 'data' ,
                        train=True,
                      download=True,
                      transform=transform)

train_dataloader = DataLoader(dataset=train,
                              batch_size=32,
                              shuffle=True)
test_dataloader = DataLoader(dataset=test,
                             batch_size=32,
                             shuffle=False)

import random
import matplotlib.pyplot as plt

train

plt.imshow(train[random.randint(0, 100)][0].squeeze())

class Net(nn.Module):
  def __init__(self, fc_input_features):
    super().__init__()

    self.conv = nn.Sequential(
        nn.Conv2d(in_channels=1, out_channels=16, kernel_size=(3, 3)),
        nn.ReLU(),

        nn.MaxPool2d(kernel_size=(2, 2)),

        nn.Conv2d(in_channels=16, out_channels=16, kernel_size=(3, 3)),
        nn.ReLU()


    )

    self.fc = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features=fc_input_features, out_features=10)
    )

  def forward(self, x):
    return self.fc(self.conv(x))

model = Net(fc_input_features=1936)
model.to(device)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

model(torch.rand(1, 1, 28, 28).to(device))

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 5

for epoch in range(epochs):
  train_loss, test_loss = 0,0

  for batch, (X, y) in enumerate(train_dataloader):
    X, y = X.to(device), y.to(device)

    y_hat = model(X)

    loss = loss_fn(y_hat, y)

    train_loss += loss.item()

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    train_loss /= len(train_dataloader)

    print(f"Train loss: {train_loss: .3f}")


with torch.inference_mode():
  for batch, (X, y) in enumerate(test_dataloader):
    X, y = X.to(device), y.to(device)

    y_hat = model(X)

    loss = loss_fn(y_hat, y)

    test_loss += loss.item()

    test_loss /= len(test_dataloader)

    print(f"Test loss: {test_loss: .3f}")

random_image = random.choice(test)

random_image_tensor = random_image[0].to(device)
random_image_label = random_image[1]

torch.softmax(model(random_image_tensor.unsqueeze(dim=0)), dim=1).argmax()

plt.imshow(random_image_tensor.squeeze().cpu(), cmap='gray')

